### ISSUE TITLE
What is "sliding" in context with neuronal networks

### ISSUE THREAD

**Issue by Zermy** [sagr4019/ResearchProject#27]

**Comment by Zermy** [comment]
Done. See wiki article.

**Comment by jan-christiansen** [comment]
Please reference the article.

**Comment by Zermy** [comment]
https://github.com/sagr4019/ResearchProject/wiki/Sliding
updated.

**Comment by jan-christiansen** [comment]
Please move the issue to "Ready for Review", if it is ready for review.

**Comment by jan-christiansen** [comment]
I still don't get what "sliding" is. Do you have any concrete examples that would illustrate the term? For example what does "reading data from structures" mean?

**Comment by Zermy** [comment]
[See article](https://github.com/sagr4019/ResearchProject/wiki/Sliding)
